# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy gh-pages

on:
    push:
        branches: ["zh"]
        paths-ignore:
            - README.md

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: zh
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install npm dependencies
              run: pnpm install
            - name: install rust pkg
              run: cargo install wasm-pack
            - name: Build
              run: pnpm run build
            - name: Configure GitHub Pages
              uses: actions/configure-pages@v4.0.0
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3.0.0
              with:
                  path: ./dist
    deploy:
        needs: build
        permissions:
            pages: "write"
            contents: "read"
        runs-on: ubuntu-20.04
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4.0.2
